# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a89dd8f01c2f0c684d592374e414c6c9d531d47818611d34a4a626a59d16da06f77f866b09b09bffaeb93dcbd6185d33fddfd19f6ca22cbe1b386f4a59d0c6d4

test:
  secret_key_base: 530478dc632edb267c4540f09bc88ab0c728497ce4695efc403a175590db4b536f8a4fa3360883f78c0db22f3ffbe7cc45df6d6692e8bbf47452323702d9a520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
